### ISSUE TITLE
Pagination and currentPage doesn't seem to work

### ISSUE THREAD

**Issue by khalwat** [markhuot/craftql#115]
This query:

```
{
  entriesConnection(section: blog, limit: 9, offset: 0) {
    totalCount
    pageInfo {
      hasPreviousPage
      hasNextPage
      currentPage
      totalPages
      first
      last
    }
}
```

Results in the expected data:

```
{
  "data": {
    "entriesConnection": {
      "totalCount": 44,
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": true,
        "currentPage": 1,
        "totalPages": 5,
        "first": 1,
        "last": 9
      }
}
```

However, if I modify the offset to be `9`:

```
{
  entriesConnection(section: blog, limit: 9, offset: 9) {
    totalCount
    pageInfo {
      hasPreviousPage
      hasNextPage
      currentPage
      totalPages
      first
      last
    }
}
```

Results in:

```
{
  "data": {
    "entriesConnection": {
      "totalCount": 44,
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": true,
        "currentPage": 1,
        "totalPages": 5,
        "first": 10,
        "last": 18
      }
}
```

I'd expect that `currentPage` would be `2`. But it seems to return `1` no matter what I do; am I  missing something?

**Comment by markhuot** [comment]
`dev-master` should fix this. By default Craft looks for `Craft::$app->getRequest()->getPageNum()` which doesn't exist within a GraphQL context. So, I overrode the `currentPage` with a manual logic. I believe the rest of `pageInfo` should work as-is but let me know if you have any more issues.

I'll leave this ticket open until this merges to master.

**Comment by markhuot** [comment]
[1.1.0](https://github.com/markhuot/craftql/blob/master/CHANGELOG.md#110---2018-06-27) was released on 2018-06-27 and includes this fix.

**Comment by alexcarpenter** [comment]
@markhuot I seem to be still experiencing this issue Andrew pointed out above. I am using version 1.1.0 of the plugin.

In the screenshot below, I would assume `currentPage` would be 4.
 
![screen shot 2018-09-13 at 1 01 33 pm](https://user-images.githubusercontent.com/825855/45503562-35f2ae00-b755-11e8-84d2-2ff12f7c3912.jpg)

**Comment by markhuot** [comment]
Are you able to try `dev-master` and see if that fixes it up for you? I've included some fixes to better pass around the `limit:` attribute.

**Comment by alexcarpenter** [comment]
On `dev-master` I am now getting `currentPage` at 5

![screen shot 2018-09-13 at 3 37 07 pm](https://user-images.githubusercontent.com/825855/45511440-ff279280-b76a-11e8-8f85-ee2f649f459b.jpg)

If I update to offset by 8 I get `currentPage` at 3

![screen shot 2018-09-13 at 3 39 07 pm](https://user-images.githubusercontent.com/825855/45511504-326a2180-b76b-11e8-830a-c4e1fe62e8b0.jpg)

**Comment by markhuot** [comment]
With 11 total entries and a limit of 3 and an offset of 9 I get the correct, `currentPage` of 4. Can you tell what commit Composer updated you too? Maybe you're one commit behind, I _just_ pushed before my last message.

![screen shot 2018-09-13 at 4 11 29 pm](https://user-images.githubusercontent.com/48975/45513129-d6ee6280-b76f-11e8-95fc-fb9a1b9800d5.png)

**Comment by alexcarpenter** [comment]
Here's what is in my composer.json file.
```
"require": {
    "craftcms/cms": "^3.0.0",
    "vlucas/phpdotenv": "^2.4.0",
    "clubstudioltd/craft-asset-rev": "v6.0.1",
    "markhuot/craftql": "dev-master"
  },
```

**Comment by markhuot** [comment]
Hrm, that's the latest version. I mimicked the same exact query and got the right `currentPage`. If possible, could you send me a database export to the email address listed on my GitHub profile? I'd like to debug this further.

**Comment by markhuot** [comment]
Okay… whoo boy, I'm a dummy. I committed half the changes, but forgot the most important part. Gah, sorry about that. `dev-master` should _now_ contain the fix. I tested this with a fresh install and don't see the issue any more.

**Comment by alexcarpenter** [comment]
Haha, no problem. It works as expected now. Thanks for the help!

**Comment by markhuot** [comment]
Closing this issue. The fix is included in version 1.2.1.

**Comment by degraaf** [comment]
Hi there, I'm getting similar problems with the response from entriesConnection in version 1.3.1. Not quite sure if this is fixed yet.

When I use an offset (for pagination), I'm getting wrong values on totalCount and pageInfo properties.

Initial query response, offset 0, limit 10:
![initial query](https://user-images.githubusercontent.com/1396033/52609227-a5212980-2ed0-11e9-9ef7-aab42bd0ebc6.png)

Response from exact same query with offset of 20 (i.e. page 3)
![query with offset](https://user-images.githubusercontent.com/1396033/52609229-a6eaed00-2ed0-11e9-8138-d1e97d029290.png)

* totalCount should be 28
* hasPreviousPage should be true
* hasNextPage should be false (this is the last page)
* currentPage is.. correct!
* totalPages should be 3
* first is correct
* last should be 28

I'm now using a work-around to add the totalCount and offset together to make sure my pagination works.
