### ISSUE TITLE
Craft Deprecation Error from GraphQL Executor

### ISSUE THREAD

**Issue by romainpoirier** [markhuot/craftql#55]
In the CP, I got this deprecation error:

> Looping through element queries directly has been deprecated. Use the all() function to fetch the query results before looping over them.

Origin: `/vendor/webonyx/graphql-php/src/Executor/Executor.php:1172`

**Comment by markhuot** [comment]
This is fixed on `dev-master` and should have only affected you if you were querying a Matrix field.

**Comment by romainpoirier** [comment]
My CraftQL seems up to date (1.0.0-beta.27), and I'm still experiencing this issue.

The entries I'm querying using CraftQL have a Matrix field, but I'm not querying this field in my queries.

**Comment by markhuot** [comment]
@romainpoirier, if you're up for it you could try `dev-master`. This fix hasn't made it to a stable release yet (it's not on `beta.27`).

**Comment by nelhop** [comment]
> Looping through element queries directly has been deprecated. Use the all() function to fetch the query results before looping over them.
> Origin: `vendor/webonyx/graphql-php/src/Executor/Executor.php:1172`

I am facing this error with a nested query:

```
fragment Group on GroupsGroup_struktur {
  headline
  text { content }
  children { id slug title }
}

query groupsList{
  groupsList: entries (
    section:[groups],
    level: 1,
    ) {
    id
    title
    ...Group
    ...on GroupsGroup_struktur {
      children {
        ...Group
      }
    }
  }
}
```

Is there a smarter / better way to do this and to avoid the error?

**Comment by jsunsawyer** [comment]
Getting the exact same error as @nelhop with what seems to be a pretty basic query. Not really sure what to be looking for to resolve this.
